services:
  backend:

    build:
      context: ./backend

    container_name: flask_backend

    restart: unless-stopped

    env_file:
      - backend/.env

    ports:
      - "5000:5000"

  frontend:

    build:
      context: ./frontend

    container_name: nginx_frontend

    restart: unless-stopped

    ports:
      - "80:80"

    depends_on:
      - backend