
services:

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    env_file:
      - backend/.env

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

  mysql:
    image: mysql:8.0

    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: autoscaling_app

    ports:
      - "3307:3306"

    volumes:
      - mysql-data:/var/lib/mysql
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql

volumes:

  mysql-data: